name: Auto Release CI

on:
  workflow_dispatch:
  schedule:
    # excute everyday on 17:00 American time
    - cron: '35 * * * *'
jobs:
  get-spray-ref:
    runs-on: ubuntu-latest
    steps:
      - name: say-hello
        run: echo "hello word"
