name: Auto Release CI

on:
  schedule:
    # excute everyday on 17:00 American time
    - cron: '0 17 * * *'

jobs:
  get-spray-ref:
    runs-on: ubuntu-latest
    steps:
      - name: say-hello
        run: echo "hello word"